#!/bin/sh

# wmp -a 0 0

# x11 environment
xset s off -dpms                                  # screen blanking
xset +fp ~/.local/share/fonts                     # custom fonts
xsetroot -cursor_name left_ptr                    # left pointer as cursor
screens                                           # set randr

back

solaar &

[ -f ~/.Xresources ] && xrdb -load ~/.Xresources
pgrep urxvtd 2> /dev/null || urxvtd -q -o -f &

# wm
bars &
snip &
sxhkd -s ~/.sxhkdfifo &
watcher &
xbanish &
envreact &

sleep 0.2
xwait
