#!/bin/sh

# load external scripts
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

wmp -a 1280 720

# x11 environment
xset s off -dpms               # screen blanking
xset +fp ~/.local/share/fonts  # custom fonts
xsetroot -cursor_name left_ptr # left pointer as cursor

back
screens pri
# autotile vert "$(lsm | grep -v "$(lsm -p)")" &

[ -f ~/.Xresources ] && xrdb -load ~/.Xresources
pgrep urxvtd 2> /dev/null || urxvtd -q -o -f &

# wm
bars &
ewmh &
sxhkd -s ~/.sxhkdfifo &
watcher &
xbanish &
envreact &


sleep 0.2
xwait
