#!/bin/sh

ACTIVE="D7D7D7"
WARNING="B23450"
INACTIVE="040404"

BW=1
ROWS=3
COLS=3
TGAP=36
IGAP=12
VGAP=12
XGAP=12
BGAP=12

MOUSE="false"
SLOPPY="true"

WORKFLOW="groups"
TERMINAL="urxvtc"

BLUR=0
WALL="$HOME/files/pictures/backs/fuji.jpg"
BACK="hsetroot -tile $WALL -gamma 0.5"
SYNCONF=${SYNCONF:-$HOME/.synergy.conf}
