#!/bin/sh
#
# configuration variables for fyre
# place in $HOME/.config/fyre/config by default

    # REQUIRED
################################################################################

# set border colours for windows
ACTIVE="D7D7D7"
WARNING="B23450" # not currently used anywhere but might be in the future
INACTIVE="404552"

# border width
BW=2

# grid based snapping
ROWS=4
COLS=4

# to get a pixel perfect gaps:
# these variables need to be divisible by the values of ROWS and COLS
IGAP=10
VGAP=10
TGAP=40
XGAP=10
BGAP=10

# mouse automatically gets moved to the middle of the window
MOUSE="false"

# moving over windows automatically focuses them
SLOPPY="true"

# set to workspaces or groups
WORKFLOW="groups"

    # OPTIONAL
################################################################################

# set path to your background - omit if you don't want fyre to manage your wall
WALL="$HOME/media/images/patterns/vertical_cloth.png"

# set integer factor to blur background by if wall program uses it
BLUR=0

# call your background program with arguments if WALL is used
BACK="hsetroot -tile $WALL"
