#!/bin/sh
#
# set colours for framebuffer

test "$TERM" = "linux" && {
    echo -en "\e]P0101010"
    echo -en "\e]P8101010"
    echo -en "\e]P1B23450"
    echo -en "\e]P9B23450"
    echo -en "\e]P2657348"
    echo -en "\e]PA657348"
    echo -en "\e]P3997849"
    echo -en "\e]PB997849"
    echo -en "\e]P47086B3"
    echo -en "\e]PC7086B3"
    echo -en "\e]P59870B3"
    echo -en "\e]PD9870B3"
    echo -en "\e]P6808080"
    echo -en "\e]PE808080"
    echo -en "\e]P7EFEFEF"
    echo -en "\e]PFEFEFEF"
}
